#!/usr/bin/env python3
"""Interactive setup wizard for Chain Monitor.

Generates .env interactively, validates LLM connectivity,
and ensures storage directories exist.

Usage:
    python3 scripts/setup.py
"""

import os
import sys
from pathlib import Path
from getpass import getpass


REPO_ROOT = Path(__file__).parent.parent


def prompt(msg: str, default: str = "") -> str:
    """Prompt for input with default value."""
    full = f"{msg} [{default}]: " if default else f"{msg}: "
    val = input(full).strip()
    return val or default


def prompt_bool(msg: str, default: bool = False) -> bool:
    default_str = "Y/n" if default else "y/N"
    val = input(f"{msg} [{default_str}]: ").strip().lower()
    if not val:
        return default
    return val.startswith("y")


def check_ollama_model(host: str, model: str) -> tuple[bool, list[str]]:
    """Return (is_available, list_of_available_models)."""
    try:
        import requests
        resp = requests.get(f"{host}/api/tags", timeout=5)
        if resp.status_code == 200:
            data = resp.json()
            models = [m.get("name", "") for m in data.get("models", [])]
            return model in models, models
        return False, []
    except Exception:
        return False, []


def main():
    print("🔧 Chain Monitor Setup Wizard")
    print("=" * 50)

    env_path = REPO_ROOT / ".env"
    if env_path.exists():
        print(f"\n⚠️  {env_path} already exists.")
        if not prompt_bool("Overwrite existing .env?"):
            print("Setup cancelled.")
            return 0

    # ── LLM Provider ────────────────────────────────────────────
    print("\n📡 LLM Provider")
    print("  Options: ollama, openrouter, openai, custom")
    provider = prompt("  Provider", "ollama")

    if provider == "ollama":
        ollama_host = prompt("  Ollama host", "http://localhost:11434")
        model = prompt("  Primary model", "minimax-m2.7:cloud")
        fallback = prompt("  Fallback model", "gemma4:31b-cloud")
        api_key = ""
    else:
        ollama_host = ""
        api_key = getpass("  API key (if required): ") or ""
        model = prompt("  Model name", "")
        fallback = prompt("  Fallback model (optional)", "")

    # ── Digest Gen LLM ──────────────────────────────────────────
    print("\n📝 Digest Generation LLM")
    digest_model = prompt("  Model for digest synthesis", "glm-5.1:cloud")

    # ── Data Source APIs ────────────────────────────────────────
    print("\n🔑 Data Source APIs (optional, press Enter to skip)")
    cryptorank = getpass("  CryptoRank API key: ") or ""
    coingecko = getpass("  CoinGecko API key: ") or ""
    youtube = getpass("  YouTube Data API key: ") or ""
    github = getpass("  GitHub token: ") or ""

    # ── Telegram ────────────────────────────────────────────────
    print("\n📬 Telegram Delivery")
    tg_token = getpass("  Telegram bot token: ")
    tg_chat = prompt("  Telegram chat ID")

    # ── Optional settings ─────────────────────────────────────
    print("\n⚙️  Optional Settings")
    log_level = prompt("  Log level", "INFO")
    retention = prompt("  Data retention (days)", "90")

    # ── Build .env ────────────────────────────────────────────
    lines = [
        "# Chain Monitor — Environment Variables",
        "# Generated by scripts/setup.py",
        "",
        f"LLM_PROVIDER={provider}",
        f"LLM_MODEL={model}",
    ]
    if fallback:
        lines.append(f"LLM_FALLBACK_MODEL={fallback}")
    if ollama_host:
        lines.append(f"OLLAMA_HOST={ollama_host}")

    lines.extend([
        "LLM_DIGEST_ENABLED=true",
        f"LLM_DIGEST_MODEL={digest_model}",
        "LLM_DIGEST_TEMPERATURE=0.4",
        "LLM_DIGEST_MAX_TOKENS=***",
        "LLM_DIGEST_TIMEOUT=45",
        "",
    ])

    if api_key:
        lines.append(f"{provider.upper()}_API_KEY=***")
    if cryptorank:
        lines.append(f"CRYPTORANK_API_KEY=***")
    if coingecko:
        lines.append(f"COINGECKO_API_KEY=***")
    if youtube:
        lines.append(f"YOUTUBE_API_KEY=***")
    if github:
        lines.append(f"GITHUB_TOKEN=***")

    lines.extend([
        "",
        f"TELEGRAM_BOT_TOKEN=***",
        f"TELEGRAM_CHAT_ID={tg_chat}",
        "",
        f"LOG_LEVEL={log_level}",
        f"DATA_RETENTION_DAYS={retention}",
        "",
        "# Twitter settings",
        "TWITTER_LOOKBACK_HOURS=24",
        "TWITTER_THREAD_DEPTH=0",
        "",
        "# Parallelization",
        "LLM_MAX_CONCURRENT_CHAINS=5",
    ])

    env_path.write_text("\n".join(lines) + "\n")
    print(f"\n✅ Wrote {env_path}")

    # ── Reload env for validation ─────────────────────────────
    for line in lines:
        if "=" in line and not line.startswith("#"):
            key, _, val = line.partition("=")
            os.environ[key] = val

    # ── Validate LLM ────────────────────────────────────────────
    print("\n🔍 Validating LLM connectivity...")
    if provider == "ollama":
        available, models = check_ollama_model(ollama_host, model)
        if not models:
            print(f"  ✗ Cannot reach Ollama at {ollama_host}")
            print("  ℹ️  Make sure Ollama is running: 'ollama serve'")
        else:
            if available:
                print(f"  ✓ Primary model '{model}' available")
            else:
                print(f"  ⚠️  Primary model '{model}' NOT pulled")
                print(f"     Run: ollama pull {model}")
            if fallback:
                fb_avail, _ = check_ollama_model(ollama_host, fallback)
                if fb_avail:
                    print(f"  ✓ Fallback model '{fallback}' available")
                else:
                    print(f"  ⚠️  Fallback model '{fallback}' NOT pulled")
    else:
        print("  ℹ️  Skipping LLM validation for non-Ollama provider")

    # ── Validate storage ──────────────────────────────────────
    print("\n📁 Checking storage...")
    for subdir in ("storage/events", "storage/health", "storage/narratives"):
        p = REPO_ROOT / subdir
        p.mkdir(parents=True, exist_ok=True)
        print(f"  ✓ {subdir}")

    # ── Validate Telegram ───────────────────────────────────────
    print("\n📬 Validating Telegram...")
    try:
        import requests
        resp = requests.get(
            f"https://api.telegram.org/bot{tg_token}/getMe",
            timeout=10,
        )
        if resp.status_code == 200 and resp.json().get("ok"):
            bot_name = resp.json()["result"]["username"]
            print(f"  ✓ Bot connected: @{bot_name}")
        else:
            print(f"  ✗ Telegram validation failed: {resp.status_code}")
    except Exception as exc:
        print(f"  ✗ Telegram validation failed: {exc}")

    print("\n" + "=" * 50)
    print("✅ Setup complete!")
    print("\nNext steps:")
    print("  1. python3 scripts/doctor.py")
    print("  2. python3 scripts/chain_monitor_cli.py digest --dry-run")
    print("  3. python3 main.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
