#!/usr/bin/env python3
"""Interactive setup wizard for Chain Monitor.

Agent-native pipeline. No LLM. No Telegram.
Generates .env, ensures storage directories exist.

Usage:
    python3 scripts/setup.py
"""

import os
import sys
from pathlib import Path
from getpass import getpass


REPO_ROOT = Path(__file__).parent.parent


def prompt(msg: str, default: str = "") -> str:
    """Prompt for input with default value."""
    full = f"{msg} [{default}]: " if default else f"{msg}: "
    val = input(full).strip()
    return val or default


def prompt_bool(msg: str, default: bool = False) -> bool:
    default_str = "Y/n" if default else "y/N"
    val = input(f"{msg} [{default_str}]: ").strip().lower()
    if not val:
        return default
    return val.startswith("y")


def main():
    print("🔧 Chain Monitor Setup Wizard")
    print("=" * 50)

    env_path = REPO_ROOT / ".env"
    if env_path.exists():
        print(f"\n⚠️  {env_path} already exists.")
        if not prompt_bool("Overwrite existing .env?"):
            print("Setup cancelled.")
            return 0

    # ── Data Source APIs ────────────────────────────────────────
    print("\n🔑 Data Source APIs (optional, press Enter to skip)")
    cryptorank = getpass("  CryptoRank API key: ") or ""
    coingecko = getpass("  CoinGecko API key: ") or ""
    youtube = getpass("  YouTube Data API key: ") or ""
    github = getpass("  GitHub token: ") or ""

    # ── Optional settings ─────────────────────────────────────
    print("\n⚙️  Optional Settings")
    log_level = prompt("  Log level", "INFO")
    retention = prompt("  Data retention (days)", "90")
    twitter_workers = prompt("  Twitter workers", "15")
    twitter_batches = prompt("  Twitter batches", "10")
    lookback = prompt("  Twitter lookback hours", "24")

    # ── Build .env ────────────────────────────────────────────
    lines = [
        "# Chain Monitor — Environment Variables",
        "# Generated by scripts/setup.py",
        "# Agent-native pipeline. No LLM. No Telegram.",
        "",
        "# Runtime settings",
        f"LOG_LEVEL={log_level}",
        f"DATA_RETENTION_DAYS={retention}",
        "",
        "# Twitter settings",
        f"TWITTER_LOOKBACK_HOURS={lookback}",
        f"TWITTER_MAX_WORKERS={twitter_workers}",
        f"TWITTER_NUM_BATCHES={twitter_batches}",
        "TWITTER_THREAD_DEPTH=0",
        "",
    ]

    if cryptorank:
        lines.append(f"CRYPTORANK_API_KEY={cryptorank}")
    if coingecko:
        lines.append(f"COINGECKO_API_KEY={coingecko}")
    if youtube:
        lines.append(f"YOUTUBE_API_KEY={youtube}")
    if github:
        lines.append(f"GITHUB_TOKEN={github}")

    lines.extend([
        "",
        "# Data source APIs (optional)",
        "# OPENROUTER_API_KEY=***",
    ])

    env_path.write_text("\n".join(lines) + "\n")
    print(f"\n✅ Wrote {env_path}")

    # ── Validate storage ──────────────────────────────────────
    print("\n📁 Checking storage...")
    for subdir in ("storage/events", "storage/health", "storage/narratives"):
        p = REPO_ROOT / subdir
        p.mkdir(parents=True, exist_ok=True)
        print(f"  ✓ {subdir}")

    # ── Agent-native delivery note ──
    print("\n📬 Note: Delivery is agent-native (no Telegram bot required)")
    print("   The running agent reads saved prompts and writes prose directly.")

    print("\n" + "=" * 50)
    print("✅ Setup complete!")
    print("\nNext steps:")
    print("  1. python3 scripts/doctor.py")
    print("  2. python3 main.py")
    print("  3. The agent running this chat will read prompts and synthesize digests")
    return 0


if __name__ == "__main__":
    sys.exit(main())
